# Generated by Django 2.1.3 on 2019-05-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='content',
            name='introduction',
        ),
    ]
