# Generated by Django 2.1.3 on 2019-05-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20190504_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
