# Generated by Django 2.1.3 on 2019-05-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_contatct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatct',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='contatct',
            old_name='last_name',
            new_name='lname',
        ),
    ]
