# Generated by Django 2.1.3 on 2019-06-14 00:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_article_title1'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body1',
            field=ckeditor.fields.RichTextField(default=True),
            preserve_default=False,
        ),
    ]
