# Generated by Django 2.1.3 on 2019-06-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20190614_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livingcost',
            name='image',
        ),
    ]
